"""A seat reserved for an authored person is that person's seat from the
moment it is minted.

Measured, chat 95 (a Star Trek story, 2026-08-28). The story was generated by
calling `generate_lived_location` with `featured_residents=` directly -- which
the public API accepts, and which RETURNS the bindings for the caller to apply
rather than applying them. So `state["bindings"] == {}` for all four registered
cast members, while their bodies carried `resident_seed_id` all along.

Both eligibility predicates read the binding and not the reservation, so:

  * `background_presence_records(95, places={"main_bridge"})` derived
    `"lieutenant_commander Data Data"` (body
    `operations_officer:featured:d3d39750b9`, `resident_seed_id="cast:75"`)
    and `"captain Jean-Luc Picard"` (`captain:featured:90cf036c97`,
    `cast:74`) as anonymous background people. `background_react` then
    selected the first on turns 2, 5, 7 and 11 and the second on turn 15 --
    five `character_bg` calls voicing a registered character in the same beat
    their own `character_major` agent ran.
  * `members_of(state, "main_bridge")` counted the same two bodies as
    anonymous crowd ground: 10 members where 8 is right.

The second-line defence could not recover it. `pick_voice_demand` excludes
registered minds by casefolded display-name equality, and the charter's
`formal_format` guarantees the derived display ("lieutenant_commander Data
Data") never equals the registered name ("Data"). Two guards, both keyed on
something that can be absent or reformatted, neither keyed on the body field
that is always there.
"""

from __future__ import annotations

import time

from world import charter_crowd
from world.charter import normalize_charter, seed_needs, seed_roster
from persist.commit import name_in_roster
from world.charter_runtime import background_presence_records, save_registry


def _chat(db):
    return db.qi(
        "INSERT INTO chats(name,scenario,created) VALUES(?,?,?)",
        ("Reserved seats", "", time.time()),
    )


def _crew(**body_over):
    """One institution, one room, one ordinary body and one reserved seat."""
    charter = normalize_charter({
        "key": "crew",
        "upkeeps": {"watch": {"place": "deck", "level": 1.0, "floor": 0.2,
                              "drift_per_hour": 0.0, "service_per_hour": 1.0}},
        "posts": {"watch_post": {"place": "deck", "serves": ["watch"],
                                 "requires": {}}},
        "bodies": {
            "ordinary": {"place": "deck", "name": "Marn Vale",
                         "competence": {}},
            "seat:featured:aa11": dict(
                {"place": "deck", "name": "Authored Person",
                 "resident_seed_id": "cast:75", "competence": {}},
                **body_over),
        },
        "priority": ["watch"],
    })
    charter["roster"] = seed_roster(charter["bodies"])
    charter["needs"] = seed_needs(charter["bodies"])
    return charter


def test_a_reserved_seat_is_never_derived_as_a_background_presence(temp_db):
    """`bindings` is empty and the reservation still answers.

    chat 95's exact shape: no binding was ever recorded, so the only fact
    distinguishing an authored person's body from an extra is the
    `resident_seed_id` minted with it.
    """
    cid = _chat(temp_db)
    state = _crew()
    assert not state.get("bindings"), "the measured case has no binding at all"
    save_registry(cid, {"crew": state})

    records = background_presence_records(cid, places={"deck"})

    assert "Authored Person" not in records
    assert set(records) == {"Marn Vale"}, (
        "a body nobody reserved is still an ordinary background presence")


def test_a_reserved_seat_is_not_counted_as_crowd_ground(temp_db):
    """The same predicate, the same wrong spelling, at the crowd floor.

    chat 95: `members_of(state, "main_bridge")` returned 10, two of them
    Picard's and Data's own bodies.
    """
    state = _crew()

    members = charter_crowd.members_of(state, "deck")

    assert "seat:featured:aa11" not in members
    assert members == ["ordinary"]


def test_a_bound_body_is_still_excluded_by_both(temp_db):
    """The half that already worked keeps working: a recorded binding is
    still an answer, it was simply never the only one."""
    cid = _chat(temp_db)
    state = _crew()
    state["bodies"]["ordinary"].pop("resident_seed_id", None)
    state["bindings"] = {"ordinary": {"char_id": 74,
                                      "name": "Marn Vale"}}
    save_registry(cid, {"crew": state})

    assert "Marn Vale" not in background_presence_records(cid, places={"deck"})
    assert charter_crowd.members_of(state, "deck") == []


def test_the_reservation_is_read_from_the_body_not_from_its_rendered_name(
        temp_db):
    """Identity is never tested by comparing rendered display strings.

    A formatter stands between the stored name and the rendered one -- chat
    95's `formal_format "{rank} {given} {family}"` rendered the registered
    character "Data" as "lieutenant_commander Data Data" -- so a rule that
    compares them is defeated by any change to presentation. Renaming the
    seat and re-ranking it must change nothing here.
    """
    cid = _chat(temp_db)
    state = _crew(name="Someone Else Entirely", rank="chief_petty_officer")
    save_registry(cid, {"crew": state})

    assert set(background_presence_records(cid, places={"deck"})) == {"Marn Vale"}
    assert charter_crowd.members_of(state, "deck") == ["ordinary"]


def test_a_stored_presence_record_is_gated_by_the_roster_not_by_string_equality():
    """A record already written keeps whatever spelling the prose gave it, and
    the gate must still recognise the person it denotes.

    Measured chat 95 turn 17 (2026-08-28). The origin fix stopped these
    records being MINTED, but two written before it stayed in
    `world['background_presences']`, and the gate tested them with bare
    casefold equality against a roster that holds bare names. So
    `captain Jean-Luc Picard` did not match `jean-luc picard`, the registered
    captain was selected as a background presence, `character_bg` produced a
    stateless line while his own `character_major` call ran in the same beat,
    and that line became the final sentence of the narrated prose with no
    notice raised.

    The widening was measured across the whole development database before it
    landed: 92 stored presences in 85 chats, 91 verdicts unchanged, exactly
    one newly excluded -- the defect itself. A title-carrying spelling of a
    registered name is the only thing this may newly exclude.
    """
    roster = {"jean-luc picard", "data", "sabine oyelaran"}

    assert name_in_roster("captain Jean-Luc Picard", roster)
    assert name_in_roster("Jean-Luc Picard", roster)
    # An ordinary background person is untouched, including one whose name
    # merely begins with a word the roster also uses.
    assert not name_in_roster("Marn Vale", roster)
    assert not name_in_roster("the captain's steward", roster)
