"""The engine's own bookkeeping is not a fact about the world.

MEASURED, live, chat 95 beat 7. The composed view delivered to a character
agent opened:

    "You are in Harbour Office. generated because no candidate described this
     location."

The second sentence is a diagnostic: a retrieval returned nothing, so the
engine invented a description and recorded why. The character read it as a
property of the room it was standing in.

It got there honestly. The mapping prompt asked the model to declare a
generated room by putting its uncertainty "in the entry's own text", and that
text becomes the room's `desc`/`notes` (`persist/commit_scene_state`) and every
observer's room notes (`agents/common._room_notes_for_view`), which
`agents/composer.environment_percept` renders verbatim. One string, two
audiences that must never be the same audience.

THE SIGNAL IS NOT THE DEFECT. A generated description that does not say it was
generated cannot be found or corrected later, which is the whole point of the
"keep a wrong guess cheap" rule this sits inside. So the two are separated
rather than one of them deleted: the prompt asks for a `provenance` FIELD, the
field is filed on the lore row's `source_notes` beside every other provenance
stamp this codebase keeps, and only what describes the place travels into a
view.

These tests are written against the CLASS -- text in which the engine talks
about its own retrieval, generation or defaults -- and never against the one
sentence that was measured. No story, place or character is named in any
assertion.
"""

from __future__ import annotations

import pytest

from agents import composer
from agents.common import _room_notes_for_view
from persist.commit import GENERATED_SOURCE_PREFIX, _file_engine_provenance
from story.provenance_text import (looks_like_engine_provenance,
                                   split_engine_provenance,
                                   strip_engine_provenance)

#: Shapes the same diagnostic arrives in. The measured one is the first; the
#: rest are the ways a model rephrases it, which is exactly how a literal guard
#: written around one string stops holding.
ENGINE_DIAGNOSTICS = (
    "generated because no candidate described this location.",
    "Generated because no candidate described this floor.",
    "This description was auto-generated.",
    "Auto-generated: canon was silent.",
    "Placeholder until an author writes this.",
    "Fallback description; retrieval returned nothing.",
    "This entry was synthesised because no lore entry covered it.",
)

#: Ordinary description that must survive untouched. Fiction is allowed to use
#: the ordinary senses of these words, and a guard that eats them has traded
#: one wrong view for another.
WORLD_PROSE = (
    "A low room with a stove. The heat generated by it reaches the door.",
    "Two chairs face each other across a table.",
    "The lamp is the only light. Beyond it the corridor is dark.",
    "A hum, generated somewhere below the floor, carries up through the "
    "boards.",
)


def _view_text(notes):
    """The prose a mind receives for a room carrying `notes`."""
    percept = composer.environment_percept("r_test", "Test Room", notes)
    return composer.render_view([percept], mode="character").text


# -------------------------------------------------------------------------
# The delivery floor: nothing composed carries the engine's bookkeeping.
# -------------------------------------------------------------------------

@pytest.mark.parametrize("diagnostic", ENGINE_DIAGNOSTICS)
def test_no_composed_view_carries_engine_diagnostic_prose(diagnostic):
    text = _view_text("A narrow room with one window. " + diagnostic)
    assert "A narrow room with one window." in text, text
    assert not looks_like_engine_provenance(text), text


@pytest.mark.parametrize("diagnostic", ENGINE_DIAGNOSTICS)
def test_the_structured_observations_carry_it_no_further(diagnostic):
    """`observations_from_render` makes the render the information budget
    byte-for-byte, so the second representation cannot smuggle back what the
    first dropped. Asserted rather than assumed: it is a separate reader."""
    percept = composer.environment_percept(
        "r_test", "Test Room", "A narrow room with one window. " + diagnostic)
    rendered = composer.render_view([percept], mode="character")
    for obs in composer.observations_from_render("1", rendered):
        assert not looks_like_engine_provenance(
            (obs.get("observed") or {}).get("text") or ""), obs


def test_a_view_whose_notes_are_nothing_but_bookkeeping_says_only_the_room():
    """The degenerate case fails toward silence. An empty description is a
    room nobody has described yet, which is true; a diagnostic is a fact the
    observer has no channel to, which is not."""
    text = _view_text("generated because no candidate described this location.")
    assert not looks_like_engine_provenance(text), text
    assert "Test Room" in text


@pytest.mark.parametrize("prose", WORLD_PROSE)
def test_ordinary_description_reaches_the_view_unchanged(prose):
    """The guard SUBTRACTS only where the engine is talking about itself. A
    room whose prose happens to use one of these words is still a room."""
    assert strip_engine_provenance(prose) == prose
    assert prose in _view_text(prose)


# -------------------------------------------------------------------------
# Both sources of a room's description, taught the same rule.
# -------------------------------------------------------------------------

def test_both_sources_of_room_notes_are_gated_the_same_way():
    """A room's description comes from the scene's own record or from the lore
    layer. Two paths computing the same thing is how one of them ends up
    untaught; `_room_notes_for_view` is the single spelling."""
    dirty = "A landing at the top of the stairs. Auto-generated: canon was silent."
    served = _room_notes_for_view({"notes": dirty}, "r_test", None, {})
    assert served == "A landing at the top of the stairs."
    assert not looks_like_engine_provenance(served)


def test_a_parenthetical_note_is_still_a_note():
    """The other shape the declaration arrives in. It ends no sentence, so a
    sentence splitter alone would keep it attached to the description."""
    prose, note = split_engine_provenance(
        "A landing at the top of the stairs "
        "(generated because no candidate described this part of the place).")
    assert prose == "A landing at the top of the stairs."
    assert "no candidate" in note


# -------------------------------------------------------------------------
# The signal survives. Separating is not deleting.
# -------------------------------------------------------------------------

def test_the_provenance_is_returned_rather_than_discarded():
    prose, note = split_engine_provenance(
        "A narrow room with one window. "
        "Generated because no candidate described this floor.")
    assert prose == "A narrow room with one window."
    assert note == "Generated because no candidate described this floor."


def test_a_declared_provenance_is_filed_on_the_entry_not_in_its_prose():
    """What the mapping prompt now asks for: a field. It has to reach a column
    a person can read, or the rule has quietly become "say nothing"."""
    op = _file_engine_provenance({
        "content": "A landing at the top of the stairs.",
        "provenance": "generated; no candidate described this part of the place",
    })
    assert op["content"] == "A landing at the top of the stairs."
    assert op["source_notes"].startswith(GENERATED_SOURCE_PREFIX)
    assert "no candidate described this part of the place" in op["source_notes"]


def test_a_provenance_sentence_in_the_text_is_moved_not_dropped():
    """The floor for a model that writes it into the prose anyway. A leak is an
    engine failure, never a model's, so the signal is recovered from wherever
    it was put rather than lost with it."""
    op = _file_engine_provenance({
        "content": "A landing at the top of the stairs. "
                   "Generated because no candidate described this floor.",
    })
    assert op["content"] == "A landing at the top of the stairs."
    assert "no candidate described this floor" in op["source_notes"]
    assert not looks_like_engine_provenance(op["content"])


def test_an_entry_with_no_provenance_is_left_exactly_as_it_was():
    op = _file_engine_provenance({"content": "A landing at the top of the stairs."})
    assert op["content"] == "A landing at the top of the stairs."
    assert "source_notes" not in op


def test_an_existing_source_note_is_kept_beside_the_new_one():
    op = _file_engine_provenance({
        "content": "A landing. Auto-generated.",
        "source_notes": "written by an earlier pass",
    })
    assert op["source_notes"].startswith("written by an earlier pass")
    assert GENERATED_SOURCE_PREFIX in op["source_notes"]
