"""A real story with the concept lab's planted memory bank (2026-09-30).

The owner: "run your own test chats, perhaps one using your synth bank planted
in a character and just running a story with them."

    ENGINE_DB=<scratch, outside the tree> python tools/concept_lab/story_run.py setup
    ENGINE_DB=... python tools/concept_lab/story_run.py opening
    ENGINE_DB=... python tools/concept_lab/story_run.py turn "what the player does"
    ENGINE_DB=... python tools/concept_lab/story_run.py look [turn_idx]

setup: a fresh database with the install's providers and settings (read-only
from the main checkout's engine.db; no host credentials), the GLM roles on
NanoGPT, capture full; Ines Calder and Teodor Lind generated by the engine's
own card generator; a Ministry clerk persona; the chat; and Ines's 240
merged memories (`bank_large.json`) planted as her pre-story past (turn_idx 0,
provenance remembered, each dated so their order survives).
"""

from __future__ import annotations

import json
import os
import sqlite3
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))

from tools.bubble_drive import _require_scratch  # noqa: E402

STATE = Path(os.environ.get("ENGINE_DB", "")).with_suffix(".story.json") if os.environ.get("ENGINE_DB") else None
SKIP_SETTINGS = {"host_pw_hash", "host_pw_salt", "host_secret", "host_secret_hash", "host_username",
                 "freesound_key", "research_key", "agent_models"}

INES = """Ines Calder, 38, the only doctor in Kessel Pass, a mountain railway town where a tunnel is being driven through the ridge. Trained as a ship's surgeon; came inland six years ago after a boy, Petr Anko, died under her knife in the old clinic on Mill Lane. Blunt, tired, dry and funny when she forgets to be careful; keeps meticulous case notes in her casebook; distrusts authority that hides things; kind in practical ways, bad at saying so. Over the last eight weeks: her estranged younger sister Lotte arrived with her daughter Mira, fleeing a violent husband, and they have just moved into the rooms above the clinic; a fever at the tunnel camp was traced by Ines to a well fouled by old mine water; the contractor's engineer Konrad Voss was exposed at a railway inquiry for faking the tunnel's gas log after an explosion killed the foreman; she found in her own old casebook that Petr had a heart murmur no surgeon could have fixed; she is close to the schoolteacher Teodor Lind; she owes the pharmacist Grete money. Drive: that no one in her care dies of something she could have seen coming. Major character."""

TEODOR = """Teodor Lind, early 40s, the new schoolteacher in Kessel Pass, a mountain railway town; came from the lowlands this autumn. Gentle, wry, patient with children, stubborn about fairness; talks too much when nervous. Teaches Ines Calder's niece Mira. He and Ines, the town doctor, have grown close over the autumn -- they kissed after a parents' evening -- and he is still learning how to be near someone who treats everyone as a patient. Drive: that every child in his room leaves able to read the world for themselves."""

PERSONA = {"name": "Klara Hess",
           "appearance": "A narrow, neat woman of thirty in a grey travelling coat and wire spectacles, a Ministry satchel over one shoulder.",
           "senses": "ordinary senses", "abilities": [],
           "public_history": "A records clerk of the Ministry of Works, sent from the capital to take full statements for the final report of the Kessel Pass inquiry.",
           "private_history": ""}

SCENARIO = """Kessel Pass, a mountain railway town, on the morning of 29 November. The railway inquiry into the tunnel explosion and the 1909 flood has closed; the contractor's engineer has been dismissed and charged. Klara Hess, a records clerk from the Ministry of Works, arrives on the 10:40 train to take a full statement from the town doctor, Ines Calder, for the inquiry's final report. The clinic stands on the main street near the station, with the doctor's rooms above it; her sister Lotte and niece Mira have just moved into the back rooms. The schoolteacher Teodor Lind has come by the clinic this morning. It is cold, and the first real snow is on the ridge."""

OPENING = "I step off the 10:40 train with my satchel, ask the stationmaster the way to the doctor's clinic, and walk up the main street to knock at its door."


def _save(d):
    STATE.write_text(json.dumps(d, indent=1))


def _load():
    return json.loads(STATE.read_text())


def setup():
    from core import db
    db.init()
    src = sqlite3.connect(f"file:{ROOT / 'engine.db'}?mode=ro", uri=True)
    src.row_factory = sqlite3.Row
    cols = [r[1] for r in src.execute("pragma table_info(providers)")]
    for row in src.execute("select * from providers where id in (1, 3, 7)"):
        db.qi(f"INSERT OR REPLACE INTO providers({','.join(cols)}) VALUES({','.join('?' * len(cols))})",
              tuple(row[c] for c in cols))
    for k, v in src.execute("select key, value from settings"):
        if k not in SKIP_SETTINGS:
            db.set_setting(k, v)
    models = json.loads(src.execute("select value from settings where key='agent_models'").fetchone()[0])
    for role, route in models.items():
        if isinstance(route, dict) and route.get("provider") == 3 and "glm" in str(route.get("model")):
            models[role] = {**route, "provider": 1, "model": "z-ai/glm-5.2"}
    # NanoGPT's plain GLM goes silent past the 30 s first-token watchdog on
    # long answers; its :thinking variant streams reasoning first (the owner's
    # replay notes). The Director and room designer keep the plain model.
    for role in ("default", "utility", "story_planner", "character_major", "character_mid", "character_bg",
                 "narrator", "dramaturge", "repair"):
        models[role] = {"provider": 1, "model": "z-ai/glm-5.2:thinking"}
    db.set_setting("agent_models", json.dumps(models))
    db.set_setting("backdrops_enabled", "0")
    db.set_setting("ambience_enabled", "0")
    db.set_setting("llm_capture_enabled", "1")
    db.set_setting("llm_capture_bodies", "full")
    print("routing:", {r: (m.get("provider"), m.get("model")) for r, m in models.items() if isinstance(m, dict)})

    import tools.mood_story_drive as msd
    app = msd._app()
    ines = app.char_generate({"prompt": INES, "language": "en"})
    teo = app.char_generate({"prompt": TEODOR, "language": "en"})
    for cid, tier in ((ines["id"], "major"), (teo["id"], "mid")):
        row = db.q("SELECT sheet FROM characters WHERE id=?", (cid,), one=True)
        sheet = json.loads(row["sheet"])
        sheet.setdefault("simulation", {})["tier"] = tier
        db.q("UPDATE characters SET sheet=? WHERE id=?", (json.dumps(sheet), cid))
    print("Ines card warnings:", ines.get("warnings"), "| Teodor:", teo.get("warnings"))
    pid = app.persona_create({"sheet": PERSONA})["id"]
    chat = app.chat_new({"name": "Kessel Pass: the statement", "language": "en", "scenario": SCENARIO})
    cid = chat["id"]
    app.chat_edit(cid, {"persona_id": pid})
    app.chat_add_char(cid, {"char_id": ines["id"], "already_known": False, "already_known_cast": True})
    app.chat_add_char(cid, {"char_id": teo["id"], "already_known": False, "already_known_cast": True})
    plant(cid, ines["id"])
    _save({"chat": cid, "ines": ines["id"], "teodor": teo["id"], "persona": pid})
    print("chat", cid, "ines", ines["id"], "teodor", teo["id"])


def plant(chat_id, char_id):
    from mind.affect_pass import feel_seeded
    from mind.memory import PRESTORY_TURN_IDX, add_memories_batch
    bank = json.loads((HERE / "bank_large.json").read_text())
    rows = []
    for m in bank["memories"]:
        date = f"{m['day']} October" if m["day"] <= 31 else f"{m['day'] - 31} November"
        text = f"({date}) What I experienced: {m['experienced']} What I did: {m['did']}"
        rows.append({"chat_id": chat_id, "char_id": char_id, "turn_id": None, "turn_idx": PRESTORY_TURN_IDX,
                     # before the story's clock began: the story opens on day 60 (29 November)
                     "encoded_at_seconds": -(60 - m["day"]) * 86400.0,
                     "kind": "episodic", "category": "episode", "provenance": "remembered",
                     "salience": 0.6, "content": text, "gist": m["experienced"][:240],
                     "event_key": f"prestory:lab:{m['id']}", "confidence": 1.0})
    for i in range(0, len(rows), 20):
        add_memories_batch(rows[i:i + 20])
        print("planted", min(i + 20, len(rows)), flush=True)
    print("felt at planting:", feel_seeded(chat_id, char_id), flush=True)


def _show(tid):
    import tools.mood_story_drive as msd
    from core.db import q
    st = _load()
    print(msd._narration(tid))
    for r in q("SELECT s.key, v.content FROM variants v JOIN steps s ON s.id=v.step_id "
               "WHERE s.turn_id=? AND s.key='interaction_loop' AND v.active=1", (tid,)):
        res = (json.loads(r["content"]).get("character_results") or {}).get(str(st["ines"])) or {}
        seq = res.get("sequence") or []
        print("\n[Ines sequence]")
        for s in seq:
            print("  -", s.get("type"), ":", str(s.get("text") or s.get("content") or "")[:300])
        print("[Ines note]", str(res.get("note") or "")[:300])
        print("[Ines continuity]", json.dumps(res.get("decision_continuity"), ensure_ascii=False)[:500])
        print("[Ines recalled ids]", len(res.get("recalled_memory_ids") or []), "| ponder:", res.get("ponder"))
        print("[asked_ponder]", res.get("asked_ponder"))
    jev = [0, 0]
    import re
    for (content,) in q("SELECT v.content FROM variants v JOIN steps s ON s.id=v.step_id WHERE s.turn_id=? AND v.active=1", (tid,)):
        for i, o in re.findall(r'"role": "jev", "requested": "[^"]+", "served": "[^"]+", "in": (\d+), "out": (\d+)', content):
            jev[0] += 1
            jev[1] += int(i)
    print(f"[jev] {jev[0]} calls, {jev[1]} input tokens (${jev[1] * 0.042e-6:.4f})")


def opening():
    import tools.mood_story_drive as msd
    st = _load()
    app = msd._app()
    tid, errors = msd.turn(app, st["chat"], OPENING)


def turn(text):
    import tools.mood_story_drive as msd
    st = _load()
    app = msd._app()
    tid, errors = msd.turn(app, st["chat"], text)
    if tid:
        print("\n------ detail ------")
        _show(tid)


def look(idx=None):
    from core.db import q
    st = _load()
    row = q("SELECT id FROM turns WHERE chat_id=? " + ("AND idx=?" if idx is not None else "ORDER BY idx DESC LIMIT 1"),
            (st["chat"], idx) if idx is not None else (st["chat"],), one=True)
    _show(row["id"])


if __name__ == "__main__":
    _require_scratch(os.environ.get("ENGINE_DB"))
    cmd = sys.argv[1]
    if cmd == "setup":
        setup()
    elif cmd == "opening":
        opening()
    elif cmd == "turn":
        turn(sys.argv[2])
    elif cmd == "look":
        look(int(sys.argv[2]) if len(sys.argv) > 2 else None)
